version = 0.1
[default.deploy.parameters]
stack_name = "cffld-feedback"
resolve_s3 = true
s3_prefix = "cffld-feedback"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "UploadedFeedbackBucketName=\"cffld-feedback-uploads\" FeedbackTriageQueueName=\"cffld-feedback-triage\" BedrockModelId=\"anthropic.claude-3-haiku-20240307-v1:0\" PostgresSecretId=\"arn:aws:secretsmanager:eu-central-1:471112519697:secret:cffld-feedback-pg-0iQYhD\" PostgresDbName=\"cffld-feedback\""
image_repositories = []
